export const languages = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'bn', name: 'বাংলা', flag: '🇧🇩' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'ur', name: 'اردو', flag: '🇵🇰' },
  { code: 'id', name: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'th', name: 'ไทย', flag: '🇹🇭' },
  { code: 'pl', name: 'Polski', flag: '🇵🇱' },
  { code: 'nl', name: 'Nederlands', flag: '🇳🇱' },
]

const translations = {
  en: {
    navbar: { problem: 'Problem', features: 'Features', calculator: 'Calculator', impact: 'Impact', tryDemo: 'Try Demo' },
    hero: { badge: 'Join 10,000+ early adopters', title1: 'Track Your Footprint.', title2: 'Save the Planet.', subtitle: 'CarbonTrace automatically calculates your carbon emissions from daily activities and connects you to certified offset projects. Small steps, massive impact.', cta1: 'Try Demo Calculator', cta2: 'Learn More', scroll: 'Scroll to explore' },
    problem: { title: 'The Climate Crisis is Personal', subtitle: "Climate change can feel overwhelming, but it starts with understanding our own impact. Most people don't know where their emissions actually come from.", stat1: 'Global fossil CO₂ emissions (approx.)', stat2: 'Average fossil CO₂ per person/year', stat3: 'Global temperature rise since pre-industrial', source1: 'Source: Global Carbon Project (2023)', source2: 'Source: Global Carbon Project / Our World in Data', source3: 'Source: IPCC AR6 / WMO' },
    features: { title: 'Everything You Need to Go Carbon Neutral', subtitle: 'CarbonTrace combines powerful tracking with simple action.', feat1Title: 'Automatic Tracking', feat1Desc: "Securely connect your spending data or manually log activities. We do the math so you don't have to.", feat2Title: 'Visual Reports', feat2Desc: 'Beautiful, easy-to-understand dashboards showing exactly where your emissions come from each month.', feat3Title: 'Certified Offsets', feat3Desc: 'Directly fund verified reforestation, clean energy, and carbon capture projects around the world.', feat4Title: 'Personal Goals', feat4Desc: 'Set monthly or yearly reduction targets and get personalized tips to lower your footprint.' },
    calculator: { title: 'Quick Carbon Calculator', subtitle: 'Get a rough estimate of your annual carbon footprint in under a minute.', lifestyle: 'Your lifestyle', reset: 'Reset', transport: 'Weekly car travel', diet: 'Diet type', electricity: 'Monthly electricity', vegan: 'Vegan', vegetarian: 'Vegetarian', averageMeat: 'Average meat consumption', highMeat: 'High meat consumption', footprint: 'Your estimated footprint', perYear: 'CO₂e per year', globalAvg: 'Global average', comparisonExcellent: 'Excellent! You are well below the global average.', comparisonGood: 'Good job! You are below the global average.', comparisonWarn: 'You are above the global average. Room for improvement!', comparisonBad: 'Your footprint is significantly higher than average.' },
    impact: { title: 'Projected Impact', subtitle: 'What CarbonTrace could achieve with 10,000 active users. These are forward-looking estimates based on verified offset project data.', impact1: 'Potential annual CO₂ offset', impact2: 'Trees we could fund annually', impact3: 'Clean energy we could support' },
    cta: { title: 'Ready to shrink your footprint?', subtitle: 'Join the waitlist and be the first to get full access when we launch.', placeholder: 'Enter your email', join: 'Join Waitlist', subscribed: 'Subscribed', noSpam: 'No spam. Unsubscribe anytime.' },
    footer: { tagline: 'Track. Reduce. Offset. Repeat.', copyright: 'Built for a better planet.' }
  },
  zh: {
    navbar: { problem: '问题', features: '功能', calculator: '计算器', impact: '影响力', tryDemo: '试用演示' },
    hero: { badge: '加入 10,000+ 早期用户', title1: '追踪你的碳足迹。', title2: '守护地球。', subtitle: 'CarbonTrace 自动计算你日常活动的碳排放，并将你与经过认证的碳抵消项目对接。小步前行，巨大影响。', cta1: '试用演示计算器', cta2: '了解更多', scroll: '向下探索' },
    problem: { title: '气候危机与每个人息息相关', subtitle: '气候变化可能让人感到不知所措，但它始于了解我们自己的影响。大多数人并不知道自己的排放究竟来自哪里。', stat1: '全球化石燃料 CO₂ 排放量（约）', stat2: '人均每年化石燃料 CO₂ 排放量', stat3: '自工业化以来全球升温幅度', source1: '来源：Global Carbon Project (2023)', source2: '来源：Global Carbon Project / Our World in Data', source3: '来源：IPCC AR6 / WMO' },
    features: { title: '实现碳中和所需的一切', subtitle: 'CarbonTrace 将强大的追踪能力与简单的行动相结合。', feat1Title: '自动追踪', feat1Desc: '安全连接你的消费数据，或手动记录活动。计算交给我们。', feat2Title: '可视化报告', feat2Desc: '美观易懂的仪表盘，每月清晰展示你的排放来源。', feat3Title: '认证抵消', feat3Desc: '直接资助经过验证的全球造林、清洁能源和碳捕捉项目。', feat4Title: '个人目标', feat4Desc: '设定月度或年度减排目标，获取量身定制的减碳建议。' },
    calculator: { title: '快速碳足迹计算器', subtitle: '不到一分钟即可估算你的年度碳足迹。', lifestyle: '你的生活方式', reset: '重置', transport: '每周驾车里程', diet: '饮食类型', electricity: '每月电费', vegan: '纯素', vegetarian: '素食', averageMeat: '平均肉食', highMeat: '高肉食', footprint: '你的预估排放量', perYear: '每年二氧化碳当量', globalAvg: '全球平均值', comparisonExcellent: '太棒了！你远低于全球平均值。', comparisonGood: '做得好！你低于全球平均值。', comparisonWarn: '你高于全球平均值。还有改进空间！', comparisonBad: '你的足迹明显高于平均水平。' },
    impact: { title: '预期影响力', subtitle: '如果拥有 10,000 名活跃用户，CarbonTrace 有望实现的成果。这些是基于经认证抵消项目数据做出的前瞻性估算。', impact1: '每年有望抵消的 CO₂', impact2: '每年有望资助种植的树木', impact3: '有望支持的清洁能源' },
    cta: { title: '准备好减少你的碳足迹了吗？', subtitle: '加入等待名单，成为首批获得完整访问权限的用户。', placeholder: '输入你的邮箱', join: '加入等待名单', subscribed: '已订阅', noSpam: '绝不发送垃圾邮件。可随时取消订阅。' },
    footer: { tagline: '追踪。减少。抵消。重复。', copyright: '为更美好的地球而造。' }
  },
  es: {
    navbar: { problem: 'Problema', features: 'Funciones', calculator: 'Calculadora', impact: 'Impacto', tryDemo: 'Probar demo' },
    hero: { badge: 'Únete a 10,000+ usuarios pioneros', title1: 'Rastrea tu Huella.', title2: 'Salva el Planeta.', subtitle: 'CarbonTrace calcula automáticamente tus emisiones de carbono de las actividades diarias y te conecta con proyectos de compensación certificados. Pequeños pasos, gran impacto.', cta1: 'Probar calculadora demo', cta2: 'Saber más', scroll: 'Desplázate para explorar' },
    problem: { title: 'La Crisis Climática es Personal', subtitle: 'El cambio climático puede resultar abrumador, pero comienza con comprender nuestro propio impacto. La mayoría de la gente no sabe de dónde provienen realmente sus emisiones.', stat1: 'Emisiones globales de CO₂ fósil (aprox.)', stat2: 'Promedio de CO₂ fósil por persona/año', stat3: 'Aumento de la temperatura global desde la era preindustrial', source1: 'Fuente: Global Carbon Project (2023)', source2: 'Fuente: Global Carbon Project / Our World in Data', source3: 'Fuente: IPCC AR6 / OMM' },
    features: { title: 'Todo lo que Necesitas para Ser Carbono Neutral', subtitle: 'CarbonTrace combina un seguimiento potente con acción sencilla.', feat1Title: 'Seguimiento Automático', feat1Desc: 'Conecta tus datos de gastos de forma segura o registra las actividades manualmente. Nosotros hacemos los cálculos.', feat2Title: 'Informes Visuales', feat2Desc: 'Paneles de control hermosos y fáciles de entender que muestran exactamente de dónde provienen tus emisiones cada mes.', feat3Title: 'Compensaciones Certificadas', feat3Desc: 'Financia directamente proyectos verificados de reforestación, energía limpia y captura de carbono en todo el mundo.', feat4Title: 'Objetivos Personales', feat4Desc: 'Establece objetivos de reducción mensuales o anuales y recibe consejos personalizados para reducir tu huella.' },
    calculator: { title: 'Calculadora Rápida de Carbono', subtitle: 'Obtén una estimación aproximada de tu huella de carbono anual en menos de un minuto.', lifestyle: 'Tu estilo de vida', reset: 'Restablecer', transport: 'Viaje semanal en coche', diet: 'Tipo de dieta', electricity: 'Factura mensual de electricidad', vegan: 'Vegano', vegetarian: 'Vegetariano', averageMeat: 'Consumo medio de carne', highMeat: 'Alto consumo de carne', footprint: 'Tu huella estimada', perYear: 'CO₂e por año', globalAvg: 'Promedio global', comparisonExcellent: '¡Excelente! Estás muy por debajo del promedio global.', comparisonGood: '¡Buen trabajo! Estás por debajo del promedio global.', comparisonWarn: 'Estás por encima del promedio global. ¡Hay margen de mejora!', comparisonBad: 'Tu huella es significativamente mayor que el promedio.' },
    impact: { title: 'Impacto Proyectado', subtitle: 'Lo que CarbonTrace podría lograr con 10,000 usuarios activos. Son estimaciones prospectivas basadas en datos de proyectos de compensación verificados.', impact1: 'Potencial de compensación anual de CO₂', impact2: 'Árboles que podríamos financiar anualmente', impact3: 'Energía limpia que podríamos apoyar' },
    cta: { title: '¿Listo para reducir tu huella?', subtitle: 'Únete a la lista de espera y sé el primero en obtener acceso completo cuando lancemos.', placeholder: 'Introduce tu correo', join: 'Unirse a la lista', subscribed: 'Suscrito', noSpam: 'Sin spam. Cancela cuando quieras.' },
    footer: { tagline: 'Rastrea. Reduce. Compensa. Repite.', copyright: 'Construido para un planeta mejor.' }
  },
  hi: {
    navbar: { problem: 'समस्या', features: 'सुविधाएँ', calculator: 'कैलकुलेटर', impact: 'प्रभाव', tryDemo: 'डेमो आज़माएँ' },
    hero: { badge: '10,000+ शुरुआती अपनाने वालों में शामिल हों', title1: 'अपने कार्बन पदचिह्न को ट्रैक करें।', title2: 'ग्रह को बचाएँ।', subtitle: 'CarbonTrace स्वचालित रूप से दैनिक गतिविधियों से आपके कार्बन उत्सर्जन की गणना करता है और आपको प्रमाणित ऑफसेट परियोजनाओं से जोड़ता है। छोटे कदम, बड़ा प्रभाव।', cta1: 'डेमो कैलकुलेटर आज़माएँ', cta2: 'और जानें', scroll: 'खोजने के लिए स्क्रॉल करें' },
    problem: { title: 'जलवायु संकट व्यक्तिगत है', subtitle: 'जलवायु परिवर्तन भारी लग सकता है, लेकिन यह हमारे स्वयं के प्रभाव को समझने से शुरू होता है। अधिकांश लोग नहीं जानते कि उनके उत्सर्जन वास्तव में कहाँ से आते हैं।', stat1: 'वैश्विक जीवाश्म CO₂ उत्सर्जन (लगभग)', stat2: 'प्रति व्यक्ति/वर्ष औसत जीवाश्म CO₂', stat3: 'औद्योगिक पूर्व युग से वैश्विक तापमान वृद्धि', source1: 'स्रोत: Global Carbon Project (2023)', source2: 'स्रोत: Global Carbon Project / Our World in Data', source3: 'स्रोत: IPCC AR6 / WMO' },
    features: { title: 'कार्बन तटस्थ होने के लिए आवश्यक सब कुछ', subtitle: 'CarbonTrace शक्तिशाली ट्रैकिंग को सरल कार्रवाई के साथ जोड़ता है।', feat1Title: 'स्वचालित ट्रैकिंग', feat1Desc: 'अपने खर्च के डेटा को सुरक्षित रूप से कनेक्ट करें या मैन्युअल रूप से गतिविधियाँ लॉग करें। हम गणना करते हैं।', feat2Title: 'दृश्य रिपोर्ट', feat2Desc: 'सुंदर, आसानी से समझने योग्य डैशबोर्ड जो हर महीने सटीक रूप से दिखाते हैं कि आपके उत्सर्जन कहाँ से आते हैं।', feat3Title: 'प्रमाणित ऑफसेट', feat3Desc: 'दुनिया भर में सत्यापित वनीकरण, स्वच्छ ऊर्जा और कार्बन कैप्चर परियोजनाओं को सीधे वित्त पोषित करें।', feat4Title: 'व्यक्तिगत लक्ष्य', feat4Desc: 'मासिक या वार्षिक कमी लक्ष्य निर्धारित करें और अपने पदचिह्न को कम करने के लिए व्यक्तिगत सुझाव प्राप्त करें।' },
    calculator: { title: 'त्वरित कार्बन कैलकुलेटर', subtitle: 'एक मिनट से भी कम समय में अपने वार्षिक कार्बन पदचिह्न का अनुमान लगाएँ।', lifestyle: 'आपकी जीवनशैली', reset: 'रीसेट', transport: 'साप्ताहिक कार यात्रा', diet: 'आहार प्रकार', electricity: 'मासिक बिजली बिल', vegan: 'शाकाहारी (वegan)', vegetarian: 'शाकाहारी', averageMeat: 'औसत मांस खपत', highMeat: 'अधिक मांस खपत', footprint: 'आपका अनुमानित पदचिह्न', perYear: 'प्रति वर्ष CO₂e', globalAvg: 'वैश्विक औसत', comparisonExcellent: 'उत्कृष्ट! आप वैश्विक औसत से बहुत नीचे हैं।', comparisonGood: 'शाबाश! आप वैश्विक औसत से नीचे हैं।', comparisonWarn: 'आप वैश्विक औसत से ऊपर हैं। सुधार की गुंजाइश है!', comparisonBad: 'आपका पदचिह्न औसत से काफी अधिक है।' },
    impact: { title: 'अनुमानित प्रभाव', subtitle: '10,000 सक्रिय उपयोगकर्ताओं के साथ CarbonTrace क्या हासिल कर सकता है। ये सत्यापित ऑफसेट प्रोजेक्ट डेटा पर आधारित अग्रदृष्टिकरण अनुमान हैं।', impact1: 'संभावित वार्षिक CO₂ ऑफसेट', impact2: 'वार्षिक वित्त पोषित किए जा सकने वाले पेड़', impact3: 'समर्थित की जा सकने वाली स्वच्छ ऊर्जा' },
    cta: { title: 'अपना पदचिह्न कम करने के लिए तैयार हैं?', subtitle: 'वेटलिस्ट में शामिल हों और लॉन्च होने पर पूर्ण पहुँच प्राप्त करने वाले पहले व्यक्ति बनें।', placeholder: 'अपना ईमेल दर्ज करें', join: 'वेटलिस्ट में शामिल हों', subscribed: 'सदस्यता ली गई', noSpam: 'कोई स्पैम नहीं। कभी भी सदस्यता समाप्त करें।' },
    footer: { tagline: 'ट्रैक। कम करें। ऑफसेट। दोहराएँ।', copyright: 'एक बेहतर ग्रह के लिए निर्मित।' }
  },
  fr: {
    navbar: { problem: 'Problème', features: 'Fonctionnalités', calculator: 'Calculateur', impact: 'Impact', tryDemo: 'Essayer la démo' },
    hero: { badge: "Rejoignez 10 000+ early adopters", title1: 'Suivez Votre Empreinte.', title2: 'Sauvez la Planète.', subtitle: 'CarbonTrace calcule automatiquement vos émissions de carbone liées à vos activités quotidiennes et vous connecte à des projets de compensation certifiés. Petits pas, impact massif.', cta1: 'Essayer le calculateur démo', cta2: 'En savoir plus', scroll: 'Faites défiler pour explorer' },
    problem: { title: "La Crise Climatique est Personnelle", subtitle: "Le changement climatique peut sembler accablant, mais il commence par la compréhension de notre propre impact. La plupart des gens ne savent pas d'où viennent réellement leurs émissions.", stat1: 'Émissions mondiales de CO₂ fossiles (env.)', stat2: 'Moyenne de tonnes de CO₂ fossiles par personne/an', stat3: "Augmentation de la température mondiale depuis l'ère préindustrielle", source1: 'Source : Global Carbon Project (2023)', source2: 'Source : Global Carbon Project / Our World in Data', source3: 'Source : GIEC AR6 / OMM' },
    features: { title: "Tout ce dont Vous Avez Besoin pour Devenir Carbone Neutre", subtitle: 'CarbonTrace combine un suivi puissant avec une action simple.', feat1Title: 'Suivi Automatique', feat1Desc: "Connectez vos données de dépenses en toute sécurité ou enregistrez les activités manuellement. Nous faisons les calculs à votre place.", feat2Title: 'Rapports Visuels', feat2Desc: "Des tableaux de bord magnifiques et faciles à comprendre montrant exactement d'où proviennent vos émissions chaque mois.", feat3Title: 'Compensations Certifiées', feat3Desc: 'Financez directement des projets vérifiés de reforestation, énergies propres et capture de carbone dans le monde entier.', feat4Title: 'Objectifs Personnels', feat4Desc: "Fixez des objectifs de réduction mensuels ou annuels et recevez des conseils personnalisés pour réduire votre empreinte." },
    calculator: { title: 'Calculateur Rapide de Carbone', subtitle: "Obtenez une estimation approximative de votre empreinte carbone annuelle en moins d'une minute.", lifestyle: 'Votre style de vie', reset: 'Réinitialiser', transport: 'Trajets hebdomadaires en voiture', diet: "Régime alimentaire", electricity: "Facture d'électricité mensuelle", vegan: 'Végétalien', vegetarian: 'Végétarien', averageMeat: 'Consommation moyenne de viande', highMeat: 'Forte consommation de viande', footprint: 'Votre empreinte estimée', perYear: 'CO₂e par an', globalAvg: 'Moyenne mondiale', comparisonExcellent: 'Excellent ! Vous êtes bien en dessous de la moyenne mondiale.', comparisonGood: 'Bon travail ! Vous êtes en dessous de la moyenne mondiale.', comparisonWarn: 'Vous êtes au-dessus de la moyenne mondiale. Marge de progression !', comparisonBad: 'Votre empreinte est significativement plus élevée que la moyenne.' },
    impact: { title: 'Impact Prévisionnel', subtitle: 'Ce que CarbonTrace pourrait accomplir avec 10 000 utilisateurs actifs. Ce sont des estimations prospectives basées sur des données de projets de compensation vérifiés.', impact1: 'Potentiel de compensation annuelle de CO₂', impact2: 'Arbres que nous pourrions financer chaque année', impact3: 'Énergie propre que nous pourrions soutenir' },
    cta: { title: "Prêt à réduire votre empreinte ?", subtitle: "Rejoignez la liste d'attente et soyez parmi les premiers à avoir un accès complet au lancement.", placeholder: 'Entrez votre email', join: "Rejoindre la liste d'attente", subscribed: 'Inscrit', noSpam: 'Pas de spam. Désinscription à tout moment.' },
    footer: { tagline: 'Suivre. Réduire. Compenser. Répéter.', copyright: 'Construit pour une planète meilleure.' }
  },
  ar: {
    navbar: { problem: 'المشكلة', features: 'الميزات', calculator: 'الحاسبة', impact: 'التأثير', tryDemo: 'جرب النموذج' },
    hero: { badge: 'انضم إلى أكثر من 10,000 مستخدم مبكر', title1: 'تتبع بصمتك.', title2: 'أنقذ الكوكب.', subtitle: 'يقوم CarbonTrace تلقائيًا بحساب انبعاثات الكربون من أنشطتك اليومية ويربطك بمشاريع تعويض معتمدة. خطوات صغيرة، تأثير ضخم.', cta1: 'جرب حاسبة العرض', cta2: 'اعرف المزيد', scroll: 'مرر للاستكشاف' },
    problem: { title: 'أزمة المناخ شخصية', subtitle: 'قد يبدو تغير المناخ ساحقًا، لكنه يبدأ بفهم تأثيرنا الخاص. معظم الناس لا يعرفون من أين تأتي انبعاثاتهم بالفعل.', stat1: 'انبعاثات CO₂ الأحفورية العالمية (تقريبية)', stat2: 'متوسط CO₂ الأحفوري للشخص/السنة', stat3: 'ارتفاع درجة الحرارة العالمية منذ العصر ما قبل الصناعي', source1: 'المصدر: Global Carbon Project (2023)', source2: 'المصدر: Global Carbon Project / Our World in Data', source3: 'المصدر: IPCC AR6 / WMO' },
    features: { title: 'كل ما تحتاجه لتحييد الكربون', subtitle: 'يجمع CarbonTrace بين التتبع القوي والعمل البسيط.', feat1Title: 'التتبع التلقائي', feat1Desc: 'اربط بيانات إنفاقك بأمان أو سجل الأنشطة يدويًا. نحن نقوم بالحسابات.', feat2Title: 'التقارير المرئية', feat2Desc: 'لوحات معلومات جميلة وسهلة الفهم تعرض بالضبط من أين تأتي انبعاثاتك كل شهر.', feat3Title: 'تعويضات معتمدة', feat3Desc: 'موّل مباشرة مشاريع التحريج والطاقة النظيفة والتقاط الكربون الموثقة حول العالم.', feat4Title: 'الأهداف الشخصية', feat4Desc: 'حدد أهدافًا شهرية أو سنوية للتخفيض واحصل على نصائح مخصصة لتقليل بصمتك.' },
    calculator: { title: 'حاسبة الكربون السريعة', subtitle: 'احصل على تقدير تقريبي لبصمتك الكربونية السنوية في أقل من دقيقة.', lifestyle: 'أسلوب حياتك', reset: 'إعادة تعيين', transport: 'السفر الأسبوعي بالسيارة', diet: 'نوع النظام الغذائي', electricity: 'فاتورة الكهرباء الشهرية', vegan: 'نباتي صرف', vegetarian: 'نباتي', averageMeat: 'استهلاك متوسط للحوم', highMeat: 'استهلاك عالٍ للحوم', footprint: 'بصمتك التقديرية', perYear: 'طن مكافئ ثاني أكسيد الكربون سنويًا', globalAvg: 'المتوسط العالمي', comparisonExcellent: 'ممتاز! أنت well below المتوسط العالمي.', comparisonGood: 'عمل رائع! أنت أقل من المتوسط العالمي.', comparisonWarn: 'أنت أعلى من المتوسط العالمي. هناك مجال للتحسن!', comparisonBad: 'بصمتك أعلى بكثير من المتوسط.' },
    impact: { title: 'التأثير المتوقع', subtitle: 'ما يمكن أن تحققه CarbonTrace مع 10,000 مستخدم نشط. هذه تقديرات استشرافية مبنية على بيانات مشاريع تعويض موثقة.', impact1: 'القدرة السنوية المحتملة على تعويض CO₂', impact2: 'الأشجار التي يمكن أن نمولها سنويًا', impact3: 'الطاقة النظيفة التي يمكن أن ندعمها' },
    cta: { title: 'مستعد لتقليل بصمتك؟', subtitle: 'انضم إلى قائمة الانتظار وكن من أوائل من يحصلون على الوصول الكامل عند الإطلاق.', placeholder: 'أدخل بريدك الإلكتروني', join: 'انضم إلى قائمة الانتظار', subscribed: 'تم الاشتراك', noSpam: 'لا رسائل مزعجة. يمكنك إلغاء الاشتراك في أي وقت.' },
    footer: { tagline: 'تتبع. تقليل. تعويض. كرر.', copyright: 'بُني من أجل كوكب أفضل.' }
  },
  pt: {
    navbar: { problem: 'Problema', features: 'Recursos', calculator: 'Calculadora', impact: 'Impacto', tryDemo: 'Experimentar demo' },
    hero: { badge: 'Junte-se a 10.000+ early adopters', title1: 'Rastreie sua Pegada.', title2: 'Salve o Planeta.', subtitle: 'O CarbonTrace calcula automaticamente suas emissões de carbono das atividades diárias e conecta você a projetos de compensação certificados. Pequenos passos, impacto massivo.', cta1: 'Experimentar calculadora demo', cta2: 'Saiba mais', scroll: 'Role para explorar' },
    problem: { title: 'A Crise Climática é Pessoal', subtitle: 'A mudança climática pode parecer esmagadora, mas começa com a compreensão do nosso próprio impacto. A maioria das pessoas não sabe de onde vêm realmente suas emissões.', stat1: 'Toneladas de CO₂ fóssil emitidas globalmente em 2023 (aprox.)', stat2: 'Média de toneladas de CO₂ fóssil por pessoa/ano', stat3: 'Aumento da temperatura global desde a era pré-industrial', source1: 'Fonte: Global Carbon Project (2023)', source2: 'Fonte: Global Carbon Project / Our World in Data', source3: 'Fonte: IPCC AR6 / OMM' },
    features: { title: 'Tudo o que Você Precisa para Ficar Carbono Neutro', subtitle: 'O CarbonTrace combina um rastreamento poderoso com ação simples.', feat1Title: 'Rastreamento Automático', feat1Desc: 'Conecte seus dados de gastos com segurança ou registre as atividades manualmente. Nós fazemos as contas.', feat2Title: 'Relatórios Visuais', feat2Desc: 'Painéis de controle bonitos e fáceis de entender mostrando exatamente de onde vêm suas emissões a cada mês.', feat3Title: 'Compensações Certificadas', feat3Desc: 'Financie diretamente projetos verificados de reflorestamento, energia limpa e captura de carbono ao redor do mundo.', feat4Title: 'Objetivos Pessoais', feat4Desc: 'Estabeleça metas mensais ou anuais de redução e receba dicas personalizadas para diminuir sua pegada.' },
    calculator: { title: 'Calculadora Rápida de Carbono', subtitle: 'Obtenha uma estimativa aproximada da sua pegada de carbono anual em menos de um minuto.', lifestyle: 'Seu estilo de vida', reset: 'Redefinir', transport: 'Viagem semanal de carro', diet: 'Tipo de dieta', electricity: 'Conta mensal de eletricidade', vegan: 'Vegano', vegetarian: 'Vegetariano', averageMeat: 'Consumo médio de carne', highMeat: 'Alto consumo de carne', footprint: 'Sua pegada estimada', perYear: 'CO₂e por ano', globalAvg: 'Média global', comparisonExcellent: 'Excelente! Você está bem abaixo da média global.', comparisonGood: 'Bom trabalho! Você está abaixo da média global.', comparisonWarn: 'Você está acima da média global. Há espaço para melhorias!', comparisonBad: 'Sua pegada é significativamente maior que a média.' },
    impact: { title: 'Impacto Projetado', subtitle: 'O que a CarbonTrace poderia alcançar com 10.000 usuários ativos. São estimativas prospectivas baseadas em dados de projetos de compensação verificados.', impact1: 'Potencial anual de compensação de CO₂', impact2: 'Árvores que poderíamos financiar anualmente', impact3: 'Energia limpa que poderíamos apoiar' },
    cta: { title: 'Pronto para reduzir sua pegada?', subtitle: 'Junte-se à lista de espera e seja um dos primeiros a ter acesso completo quando lançarmos.', placeholder: 'Digite seu email', join: 'Entrar na lista de espera', subscribed: 'Inscrito', noSpam: 'Sem spam. Cancele a qualquer momento.' },
    footer: { tagline: 'Rastreie. Reduza. Compense. Repita.', copyright: 'Construído para um planeta melhor.' }
  },
  bn: {
    navbar: { problem: 'সমস্যা', features: 'বৈশিষ্ট্য', calculator: 'ক্যালকুলেটর', impact: 'প্রভাব', tryDemo: 'ডেমো দেখুন' },
    hero: { badge: '10,000+ প্রারম্ভিক গ্রহণকারীর সাথে যোগ দিন', title1: 'আপনার কার্বন পদচিহ্ন ট্র্যাক করুন।', title2: 'পৃথিবী বাঁচান।', subtitle: 'CarbonTrace স্বয়ংক্রিয়ভাবে দৈনন্দিন কার্যকলাপ থেকে আপনার কার্বন নিঃসরণ গণনা করে এবং আপনাকে স্বীকৃত অফসেট প্রকল্পের সাথে সংযুক্ত করে। ছোট পদক্ষেপ, বিশাল প্রভাব।', cta1: 'ডেমো ক্যালকুলেটর দেখুন', cta2: 'আরও জানুন', scroll: 'অন্বেষণ করতে স্ক্রল করুন' },
    problem: { title: 'জলবায়ু সংকট ব্যক্তিগত', subtitle: 'জলবায়ু পরিবর্তন অভিভূত হতে পারে, কিন্তু এটি আমাদের নিজস্ব প্রভাব বোঝা দিয়ে শুরু হয়। বেশিরভাগ মানুষ জানে না তাদের নিঃসরণ আসলে কোথা থেকে আসে।', stat1: 'বিশ্বব্যাপী জীবাশ্ম CO₂ নির্গমন (প্রায়)', stat2: 'প্রতি ব্যক্তি/বছরে গড় জীবাশ্ম CO₂', stat3: 'পূর্ব-শিল্পযুগ থেকে বিশ্বব্যাপী তাপমাত্রা বৃদ্ধি', source1: 'উৎস: Global Carbon Project (2023)', source2: 'উৎস: Global Carbon Project / Our World in Data', source3: 'উৎস: IPCC AR6 / WMO' },
    features: { title: 'কার্বন নিরপেক্ষ হতে যা কিছু প্রয়োজন', subtitle: 'CarbonTrace শক্তিশালী ট্র্যাকিংকে সহজ কর্মের সাথে যুক্ত করে।', feat1Title: 'স্বয়ংক্রিয় ট্র্যাকিং', feat1Desc: 'নিরাপদে আপনার ব্যয়ের ডেটা সংযুক্ত করুন বা ম্যানুয়ালি কার্যকলাপ লগ ইন করুন। আমরা গণনা করি।', feat2Title: 'ভিজ্যুয়াল রিপোর্ট', feat2Desc: 'সুন্দর, সহজবোধ্য ড্যাশবোর্ড যা প্রতি মাসে ঠিক আপনার নিঃসরণ কোথা থেকে আসে তা দেখায়।', feat3Title: 'স্বীকৃত অফসেট', feat3Desc: 'বিশ্বজুড়ে যাচাইকৃত বনায়ন, পরিষ্কার শক্তি এবং কার্বন ধরন প্রকল্পে সরাসরি অর্থায়ন করুন।', feat4Title: 'ব্যক্তিগত লক্ষ্য', feat4Desc: 'মাসিক বা বাৎসরিক হ্রাস লক্ষ্য নির্ধারণ করুন এবং আপনার পদচিহ্ন কমাতে ব্যক্তিগতকৃত পরামর্শ পান।' },
    calculator: { title: 'দ্রুত কার্বন ক্যালকুলেটর', subtitle: 'এক মিনিটেরও কম সময়ে আপনার বার্ষিক কার্বন পদচিহ্নের একটি আনুমানিক ধারণা পান।', lifestyle: 'আপনার জীবনধারা', reset: 'রিসেট', transport: 'সাপ্তাহিক গাড়ি ভ্রমণ', diet: 'খাদ্যের ধরন', electricity: 'মাসিক বিদ্যুৎ বিল', vegan: 'ভেগান', vegetarian: 'নিরামিষাশী', averageMeat: 'গড় মাংস খাওয়া', highMeat: 'বেশি মাংস খাওয়া', footprint: 'আপনার আনুমানিক পদচিহ্ন', perYear: 'প্রতি বছর CO₂e', globalAvg: 'বিশ্বব্যাপী গড়', comparisonExcellent: 'দারুণ! আপনি বিশ্বব্যাপী গড়ের অনেক নিচে আছেন।', comparisonGood: 'ভালো কাজ! আপনি বিশ্বব্যাপী গড়ের নিচে আছেন।', comparisonWarn: 'আপনি বিশ্বব্যাপী গড়ের উপরে আছেন। উন্নতির জায়গা আছে!', comparisonBad: 'আপনার পদচিহ্ন গড়ের চেয়ে উল্লেখযোগ্যভাবে বেশি।' },
    impact: { title: 'পূর্বাভাসিত প্রভাব', subtitle: '১০,০০০ সক্রিয় ব্যবহারকারী নিয়ে CarbonTrace যা অর্জন করতে পারে। এগুলো যাচাইকৃত অফসেট প্রকল্পের তথ্যের উপর ভিত্তি করে প্রস্তাবিত অনুমান।', impact1: 'সম্ভাব্য বার্ষিক CO₂ অফসেট', impact2: 'বার্ষিক অর্থায়ন করা যেতে পারে এমন গাছ', impact3: 'সমর্থন করা যেতে পারে এমন পরিষ্কার শক্তি' },
    cta: { title: 'আপনার পদচিহ্ন কমাতে প্রস্তুত?', subtitle: 'ওয়েটলিস্টে যোগ দিন এবং আমরা লঞ্চ করলে সম্পূর্ণ অ্যাক্সেস পাওয়া প্রথম ব্যক্তিদের একজন হন।', placeholder: 'আপনার ইমেইল লিখুন', join: 'ওয়েটলিস্টে যোগ দিন', subscribed: 'সাবস্ক্রাইব করা হয়েছে', noSpam: 'কোনো স্প্যাম নয়। যেকোনো সময় আনসাবস্ক্রাইব করুন।' },
    footer: { tagline: 'ট্র্যাক। কমান। অফসেট। পুনরাবৃত্তি।', copyright: 'একটি ভালো গ্রহের জন্য নির্মিত।' }
  },
  ru: {
    navbar: { problem: 'Проблема', features: 'Функции', calculator: 'Калькулятор', impact: 'Влияние', tryDemo: 'Попробовать демо' },
    hero: { badge: 'Присоединяйтесь к 10 000+ ранним пользователям', title1: 'Отслеживай Свой След.', title2: 'Спаси Планету.', subtitle: 'CarbonTrace автоматически рассчитывает ваши выбросы углерода от повседневной деятельности и связывает вас с сертифицированными проектами компенсации. Маленькие шаги, огромный эффект.', cta1: 'Попробовать демо-калькулятор', cta2: 'Узнать больше', scroll: 'Прокрутите, чтобы исследовать' },
    problem: { title: 'Климатический Кризис — Это Личное', subtitle: 'Изменение климата может казаться подавляющим, но оно начинается с понимания нашего собственного влияния. Большинство людей не знают, откуда на самом деле берутся их выбросы.', stat1: 'Тонн CO₂ от ископаемого топлива, выброшенных глобально (прибл.)', stat2: 'Среднее количество тонн CO₂ на человека/год', stat3: 'Глобальное повышение температуры с доиндустриальной эпохи', source1: 'Источник: Global Carbon Project (2023)', source2: 'Источник: Global Carbon Project / Our World in Data', source3: 'Источник: МГЭИК AR6 / ВМО' },
    features: { title: 'Всё Необходимое для Углеродной Нейтральности', subtitle: 'CarbonTrace сочетает мощное отслеживание с простыми действиями.', feat1Title: 'Автоматическое Отслеживание', feat1Desc: 'Безопасно подключите данные о своих расходах или регистрируйте активность вручную. Мы сделаем расчёты за вас.', feat2Title: 'Визуальные Отчёты', feat2Desc: 'Красивые, легко понятные панели, которые точно показывают, откуда каждый месяц берутся ваши выбросы.', feat3Title: 'Сертифицированные Компенсации', feat3Desc: 'Напрямую финансируйте проверенные проекты по лесовосстановлению, чистой энергии и улавливанию углерода по всему миру.', feat4Title: 'Личные Цели', feat4Desc: 'Устанавливайте ежемесячные или годовые цели по сокращению выбросов и получайте персонализированные советы.' },
    calculator: { title: 'Быстрый Углеродный Калькулятор', subtitle: 'Получите приблизительную оценку вашего годового углеродного следа менее чем за минуту.', lifestyle: 'Ваш образ жизни', reset: 'Сбросить', transport: 'Еженедельные поездки на машине', diet: 'Тип диеты', electricity: 'Ежемесячный счёт за электроэнергию', vegan: 'Веган', vegetarian: 'Вегетарианец', averageMeat: 'Среднее потребление мяса', highMeat: 'Высокое потребление мяса', footprint: 'Ваш расчётный след', perYear: 'CO₂e в год', globalAvg: 'Глобальное среднее', comparisonExcellent: 'Отлично! Вы значительно ниже глобального среднего.', comparisonGood: 'Отличная работа! Вы ниже глобального среднего.', comparisonWarn: 'Вы выше глобального среднего. Есть куда стремиться!', comparisonBad: 'Ваш след значительно выше среднего.' },
    impact: { title: 'Прогнозируемый Влияние', subtitle: 'Чего CarbonTrace мог бы достичь с 10 000 активными пользователями. Это прогнозные оценки на основе данных проверенных проектов компенсации.', impact1: 'Потенциальное годовое поглощение CO₂', impact2: 'Деревьев, которые мы могли бы финансировать ежегодно', impact3: 'Чистой энергии, которую мы могли бы поддерживать' },
    cta: { title: 'Готовы уменьшить свой след?', subtitle: 'Присоединяйтесь к списку ожидания и будьте одним из первых, кто получит полный доступ к запуску.', placeholder: 'Введите ваш email', join: 'Встать в очередь', subscribed: 'Подписано', noSpam: 'Никакого спама. Отписка в любое время.' },
    footer: { tagline: 'Отслеживай. Сокращай. Компенсируй. Повторяй.', copyright: 'Создано для лучшей планеты.' }
  },
  ur: {
    navbar: { problem: 'مسئلہ', features: 'خصوصیات', calculator: 'کیلکولیٹر', impact: 'اثر', tryDemo: 'ڈیمو آزمائیں' },
    hero: { badge: '10,000+ ابتدائی صارفین میں شامل ہوں', title1: 'اپنے کاربن فوٹ پرنٹ کا پتہ لگائیں۔', title2: 'سیارے کو بچائیں۔', subtitle: 'CarbonTrace خود بخود آپ کی روزمرہ کی سرگرمیوں سے کاربن کے اخراجات کا حساب لگاتا ہے اور آپ کو تصدیق شدہ آفسیٹ پروجیکٹس سے جوڑتا ہے۔ چھوٹے قدم، زبردست اثر۔', cta1: 'ڈیمو کیلکولیٹر آزمائیں', cta2: 'مزید جانیں', scroll: 'دریافت کرنے کے لیے سکرول کریں' },
    problem: { title: 'موسمیاتی بحران ذاتی ہے', subtitle: 'آب و ہوا میں تبدیل بہت بڑی لگ سکتی ہے، لیکن یہ ہمارے اپنے اثر کو سمجھنے سے شروع ہوتی ہے۔ زیادہ تر لوگ نہیں جانتے کہ ان کے اخراجات اصل میں کہاں سے آتے ہیں۔', stat1: 'عالمی فوسل CO₂ اخراج (تقریباً)', stat2: 'فی کس/سال اوسط فوسل CO₂', stat3: 'صنعتی دور سے عالمی درجہ حرارت میں اضافہ', source1: 'ماخذ: Global Carbon Project (2023)', source2: 'ماخذ: Global Carbon Project / Our World in Data', source3: 'ماخذ: IPCC AR6 / WMO' },
    features: { title: 'کاربن نیوٹرل ہونے کے لیے درکار ہر چیز', subtitle: 'CarbonTrace طاقتور ٹریکنگ کو آسان عمل کے ساتھ جوڑتا ہے۔', feat1Title: 'خودکار ٹریکنگ', feat1Desc: 'محفوظ طریقے سے اپنے اخراجات کا ڈیٹا جوڑیں یا سرگرمیاں دستی طور پر لاگ کریں۔ ہم حساب کتاب کرتے ہیں۔', feat2Title: 'بصری رپورٹس', feat2Desc: 'خوبصورت، آسانی سے سمجھنے والے ڈیش بورڈ جو بالکل درست بتاتے ہیں کہ ہر مہینے آپ کے اخراجات کہاں سے آتے ہیں۔', feat3Title: 'تصدیق شدہ آفسیٹ', feat3Desc: 'دنیا بھر میں تصدیق شدہ جنگل کاری، صاف توانائی اور کاربن کیپچر پراجیکٹس کو براہ راست فنڈ کریں۔', feat4Title: 'ذاتی اہداف', feat4Desc: 'ماہانہ یا سالانہ کم کے اہداف طے کریں اور اپنے فوٹ پرنٹ کو کم کرنے کے لیے ذاتی مشورے حاصل کریں۔' },
    calculator: { title: 'فوری کاربن کیلکولیٹر', subtitle: 'ایک منٹ سے بھی کم میں اپنے سالانہ کاربن فوٹ پرنٹ کا تخمینہ لگائیں۔', lifestyle: 'آپ کا طرز زندگی', reset: 'ری سیٹ', transport: 'ہفتہ وار گاڑی کا سفر', diet: 'خوراک کی قسم', electricity: 'ماہانہ بجلی کا بل', vegan: 'مکمل نباتاتی', vegetarian: 'نباتاتی', averageMeat: 'اوسط گوشت کا استعمال', highMeat: 'زیادہ گوشت کا استعمال', footprint: 'آپ کا تخمینہ شدہ فوٹ پرنٹ', perYear: 'فی سال CO₂e', globalAvg: 'عالمی اوسط', comparisonExcellent: 'بہترین! آپ عالمی اوسط سے بہت نیچے ہیں۔', comparisonGood: 'بہت خوب! آپ عالمی اوسط سے نیچے ہیں۔', comparisonWarn: 'آپ عالمی اوسط سے اوپر ہیں۔ بہتری کی گنجائش ہے!', comparisonBad: 'آپ کا فوٹ پرنٹ اوسط سے نمایاں طور پر زیادہ ہے۔' },
    impact: { title: 'متوقع اثر', subtitle: '10,000 فعال صارفین کے ساتھ CarbonTrace کیا حاصل کر سکتا ہے۔ یہ تصدیق شدہ آفسیٹ منصوبوں کے ڈیٹا پر مبنی پیش نظارہ اندازے ہیں۔', impact1: 'ممکنہ سالانہ CO₂ آفسیٹ', impact2: 'سالانہ مالی اعانت کے قابل درخت', impact3: 'سہارا دی جا سکنے والی صاف توانائی' },
    cta: { title: 'اپنا فوٹ پرنٹ کم کرنے کے لیے تیار ہیں؟', subtitle: 'انتظار کی فہرست میں شامل ہوں اور لانچ ہونے پر مکمل رسائی حاصل کرنے والے پہلے افراد میں شامل ہوں۔', placeholder: 'اپنا ای میل درج کریں', join: 'انتظار کی فہرست میں شامل ہوں', subscribed: 'سبسکرائب ہو گیا', noSpam: 'کوئی سپیم نہیں۔ کسی بھی وقت سبسکرپشن ختم کریں۔' },
    footer: { tagline: 'ٹریک کریں۔ کم کریں۔ آفسیٹ کریں۔ دہرائیں۔', copyright: 'ایک بہتر سیارے کے لیے تعمیر کیا گیا۔' }
  },
  id: {
    navbar: { problem: 'Masalah', features: 'Fitur', calculator: 'Kalkulator', impact: 'Dampak', tryDemo: 'Coba Demo' },
    hero: { badge: 'Bergabung dengan 10.000+ pengguna awal', title1: 'Lacak Jejakmu.', title2: 'Selamatkan Bumi.', subtitle: 'CarbonTrace secara otomatis menghitung emisi karbon dari aktivitas harian Anda dan menghubungkan Anda dengan proyek offset bersertifikat. Langkah kecil, dampak besar.', cta1: 'Coba Kalkulator Demo', cta2: 'Pelajari Lebih Lanjut', scroll: 'Gulir untuk menjelajah' },
    problem: { title: 'Krisis Iklim adalah Pribadi', subtitle: 'Perubahan iklim bisa terasa luar biasa, tapi itu dimulai dari memahami dampak kita sendiri. Kebanyakan orang tidak tahu dari mana sebenarnya emisi mereka berasal.', stat1: 'Emisi CO₂ fosil global (kira-kira)', stat2: 'Rata-rata ton CO₂ fosil per orang/tahun', stat3: 'Kenaikan suhu global sejak era pra-industri', source1: 'Sumber: Global Carbon Project (2023)', source2: 'Sumber: Global Carbon Project / Our World in Data', source3: 'Sumber: IPCC AR6 / WMO' },
    features: { title: 'Semua yang Anda Butuhkan untuk Netral Karbon', subtitle: 'CarbonTrace menggabungkan pelacakan yang kuat dengan tindakan sederhana.', feat1Title: 'Pelacakan Otomatis', feat1Desc: 'Hubungkan data pengeluaran Anda dengan aman atau catat aktivitas secara manual. Kami yang menghitung.', feat2Title: 'Laporan Visual', feat2Desc: 'Dasbor yang indah dan mudah dipahami menunjukkan dengan tepat dari mana emisi Anda berasal setiap bulan.', feat3Title: 'Offset Bersertifikat', feat3Desc: 'Danai langsung proyek reboisasi, energi bersih, dan penangkapan karbon terverifikasi di seluruh dunia.', feat4Title: 'Tujuan Pribadi', feat4Desc: 'Tetapkan target pengurangan bulanan atau tahunan dan dapatkan tips personal untuk mengurangi jejak karbon Anda.' },
    calculator: { title: 'Kalkulator Karbon Cepat', subtitle: 'Dapatkan perkiraan jejak karbon tahunan Anda dalam waktu kurang dari satu menit.', lifestyle: 'Gaya hidup Anda', reset: 'Atur Ulang', transport: 'Perjalanan mobil mingguan', diet: 'Jenis diet', electricity: 'Tagihan listrik bulanan', vegan: 'Vegan', vegetarian: 'Vegetarian', averageMeat: 'Konsumsi daging rata-rata', highMeat: 'Konsumsi daging tinggi', footprint: 'Perkiraan jejak Anda', perYear: 'CO₂e per tahun', globalAvg: 'Rata-rata global', comparisonExcellent: 'Hebat! Anda jauh di bawah rata-rata global.', comparisonGood: 'Kerja bagus! Anda di bawah rata-rata global.', comparisonWarn: 'Anda di atas rata-rata global. Masih ada ruang untuk perbaikan!', comparisonBad: 'Jejak Anda secara signifikan lebih tinggi dari rata-rata.' },
    impact: { title: 'Dampak Proyeksi', subtitle: 'Apa yang bisa dicapai CarbonTrace dengan 10.000 pengguna aktif. Ini adalah estimasi prospektif berdasarkan data proyek offset terverifikasi.', impact1: 'Potensi offset CO₂ tahunan', impact2: 'Pohon yang bisa kami danai setiap tahun', impact3: 'Energi bersih yang bisa kami dukung' },
    cta: { title: 'Siap mengecilkan jejakmu?', subtitle: 'Bergabunglah dengan daftar tunggu dan jadilah salah satu yang pertama mendapatkan akses penuh saat peluncuran.', placeholder: 'Masukkan email Anda', join: 'Gabung Daftar Tunggu', subscribed: 'Berlangganan', noSpam: 'Tidak ada spam. Berhenti berlangganan kapan saja.' },
    footer: { tagline: 'Lacak. Kurangi. Offset. Ulangi.', copyright: 'Dibangun untuk planet yang lebih baik.' }
  },
  de: {
    navbar: { problem: 'Problem', features: 'Funktionen', calculator: 'Rechner', impact: 'Impact', tryDemo: 'Demo testen' },
    hero: { badge: 'Schließe dich 10.000+ Early Adopters an', title1: 'Verfolge deinen Fußabdruck.', title2: 'Rette den Planeten.', subtitle: 'CarbonTrace berechnet automatisch deine CO₂-Emissionen aus alltäglichen Aktivitäten und verbindet dich mit zertifizierten Kompensationsprojekten. Kleine Schritte, massive Wirkung.', cta1: 'Demo-Rechner testen', cta2: 'Mehr erfahren', scroll: 'Scrolle, um zu erkunden' },
    problem: { title: 'Die Klimakrise ist persönlich', subtitle: 'Der Klimawandel kann überwältigend wirken, aber er beginnt mit dem Verständnis unserer eigenen Auswirkungen. Die meisten Menschen wissen nicht, woher ihre Emissionen tatsächlich kommen.', stat1: 'Globale fossile CO₂-Emissionen (ca.)', stat2: 'Durchschnittliche fossile CO₂ pro Person/Jahr', stat3: 'Globaler Temperaturanstieg seit der vorindustriellen Zeit', source1: 'Quelle: Global Carbon Project (2023)', source2: 'Quelle: Global Carbon Project / Our World in Data', source3: 'Quelle: IPCC AR6 / WMO' },
    features: { title: 'Alles, was du für Klimaneutralität brauchst', subtitle: 'CarbonTrace vereint leistungsstarkes Tracking mit einfacher Umsetzung.', feat1Title: 'Automatisches Tracking', feat1Desc: 'Verbinde sicher deine Ausgabendaten oder protokolliere Aktivitäten manuell. Wir übernehmen die Berechnung.', feat2Title: 'Visuelle Berichte', feat2Desc: 'Wunderschöne, leicht verständliche Dashboards, die genau zeigen, woher deine Emissionen jeden Monat kommen.', feat3Title: 'Zertifizierte Kompensationen', feat3Desc: 'Finanziere direkt verifizierte Aufforstungs-, saubere Energie- und Carbon-Capture-Projekte weltweit.', feat4Title: 'Persönliche Ziele', feat4Desc: 'Setze monatliche oder jährliche Reduktionsziele und erhalte personalisierte Tipps zur Reduzierung deines Fußabdrucks.' },
    calculator: { title: 'Schneller CO₂-Rechner', subtitle: 'Erhalte eine grobe Schätzung deines jährlichen CO₂-Fußabdrucks in weniger als einer Minute.', lifestyle: 'Dein Lebensstil', reset: 'Zurücksetzen', transport: 'Wöchentliche Autofahrten', diet: 'Ernährungstyp', electricity: 'Monatliche Stromrechnung', vegan: 'Vegan', vegetarian: 'Vegetarisch', averageMeat: 'Durchschnittlicher Fleischkonsum', highMeat: 'Hoher Fleischkonsum', footprint: 'Dein geschätzter Fußabdruck', perYear: 'CO₂e pro Jahr', globalAvg: 'Weltweiter Durchschnitt', comparisonExcellent: 'Hervorragend! Du liegst weit unter dem weltweiten Durchschnitt.', comparisonGood: 'Gute Arbeit! Du liegst unter dem weltweiten Durchschnitt.', comparisonWarn: 'Du liegst über dem weltweiten Durchschnitt. Es gibt Verbesserungspotenzial!', comparisonBad: 'Dein Fußabdruck ist deutlich höher als der Durchschnitt.' },
    impact: { title: 'Erwartete Wirkung', subtitle: 'Was CarbonTrace mit 10.000 aktiven Nutzern erreichen könnte. Dies sind vorausschauende Schätzungen basierend auf Daten verifizierter Kompensationsprojekte.', impact1: 'Mögliche jährliche CO₂-Kompensation', impact2: 'Bäume, die wir jährlich finanzieren könnten', impact3: 'Saubere Energie, die wir unterstützen könnten' },
    cta: { title: 'Bereit, deinen Fußabdruck zu verkleinern?', subtitle: 'Trage dich auf die Warteliste ein und sei einer der Ersten, der beim Launch vollen Zugriff erhält.', placeholder: 'E-Mail eingeben', join: 'Warteliste beitreten', subscribed: 'Abonniert', noSpam: 'Kein Spam. Jederzeit abbestellbar.' },
    footer: { tagline: 'Verfolgen. Reduzieren. Kompensieren. Wiederholen.', copyright: 'Gebaut für einen besseren Planeten.' }
  },
  ja: {
    navbar: { problem: '問題', features: '機能', calculator: '計算機', impact: 'インパクト', tryDemo: 'デモを試す' },
    hero: { badge: '10,000人以上の早期ユーザーに参加', title1: 'あなたのフットプリントを追跡。', title2: '地球を守ろう。', subtitle: 'CarbonTraceは、日常の活動から自動的に炭素排出量を計算し、認証されたオフセットプロジェクトにつなげます。小さな一歩が、大きな変化を生み出します。', cta1: 'デモ計算機を試す', cta2: '詳細を見る', scroll: 'スクロールして探索' },
    problem: { title: '気候危機は私たち一人ひとりの問題', subtitle: '気候変動は圧倒的に感じられるかもしれませんが、それは自分自身の影響を理解することから始まります。多くの人は、自分の排出量が実際にどこから来ているのか知りません。', stat1: '世界の化石燃料由来 CO₂ 排出量（概算）', stat2: '1人あたりの年平均化石燃料由来 CO₂ 排出量', stat3: '産業革命前からの地球の気温上昇', source1: '出典: Global Carbon Project (2023)', source2: '出典: Global Carbon Project / Our World in Data', source3: '出典: IPCC AR6 / WMO' },
    features: { title: 'カーボンニュートラルに必要なすべて', subtitle: 'CarbonTraceは、強力な追跡機能とシンプルな行動を組み合わせます。', feat1Title: '自動追跡', feat1Desc: '支出データを安全に連携するか、手動で活動を記録してください。計算は私たちが行います。', feat2Title: 'ビジュアルレポート', feat2Desc: '美しく簡単に理解できるダッシュボードで、毎月の排出量の発生源を正確に把握できます。', feat3Title: '認証オフセット', feat3Desc: '世界中の検証済み森林再生、クリーンエネルギー、カーボンキャプチャプロジェクトに直接資金を提供します。', feat4Title: '個人目標', feat4Desc: '月次または年次の削減目標を設定し、フットプリントを減らすためのパーソナライズされたヒントを受け取ります。' },
    calculator: { title: 'クイックカーボン計算機', subtitle: '1分もかからず、あなたの年間カーボンフットプリントのおおよその推定値を取得できます。', lifestyle: 'あなたのライフスタイル', reset: 'リセット', transport: '週間の車での移動距離', diet: '食事のタイプ', electricity: '月々の電気代', vegan: 'ビーガン', vegetarian: 'ベジタリアン', averageMeat: '平均的な肉消費', highMeat: '多い肉消費', footprint: '推定フットプリント', perYear: '年間CO₂e', globalAvg: '世界平均', comparisonExcellent: '素晴らしい！世界平均を大幅に下回っています。', comparisonGood: 'よくできました！世界平均を下回っています。', comparisonWarn: '世界平均を上回っています。改善の余地があります！', comparisonBad: 'あなたのフットプリントは平均よりもかなり高いです。' },
    impact: { title: '予測されるインパクト', subtitle: '10,000人のアクティブユーザーを抱えた場合に CarbonTrace が達成できる可能性のある成果。これらは、検証済みオフセットプロジェクトのデータに基づく前向きな見積もりです。', impact1: '年間の潜在的 CO₂ オフセット量', impact2: '年間に資金提供できる可能性のある木々', impact3: '支援できる可能性のあるクリーンエネルギー' },
    cta: { title: 'フットプリントを小さくする準備はできましたか？', subtitle: 'ウェイトリストに登録して、ローンチ時に最初にフルアクセスを得る人になりましょう。', placeholder: 'メールアドレスを入力', join: 'ウェイトリストに登録', subscribed: '登録完了', noSpam: 'スパムはありません。いつでも解除できます。' },
    footer: { tagline: '追跡。削減。オフセット。繰り返す。', copyright: 'より良い地球のために作られました。' }
  },
  tr: {
    navbar: { problem: 'Sorun', features: 'Özellikler', calculator: 'Hesaplayıcı', impact: 'Etki', tryDemo: 'Demoyu Dene' },
    hero: { badge: '10.000+ erken benimseyen aramıza katıl', title1: 'Ayak İzini Takip Et.', title2: 'Gezegeni Kurtar.', subtitle: 'CarbonTrace, günlük aktivitelerinden otomatik olarak karbon emisyonlarını hesaplar ve seni sertifikalı dengeleme projeleriyle bağlar. Küçük adımlar, büyük etki.', cta1: 'Demo Hesaplayıcıyı Dene', cta2: 'Daha Fazla Bilgi', scroll: 'Keşfetmek için kaydır' },
    problem: { title: 'İklim Krişi Kişiseldir', subtitle: 'İklim değişikliği bunaltıcı gelebilir, ama kendi etkimizi anlamakla başlar. Çoğu insan emisyonlarının gerçekte nereden geldiğini bilmiyor.', stat1: 'Küresel fosil CO₂ emisyonları (yakl.)', stat2: 'Kişi başına yıllık ortalama fosil CO₂', stat3: 'Sanayi öncesi dönemden bu yana küresel sıcaklık artışı', source1: 'Kaynak: Global Carbon Project (2023)', source2: 'Kaynak: Global Carbon Project / Our World in Data', source3: 'Kaynak: IPCC AR6 / WMO' },
    features: { title: 'Karbon Nötr Olmak İçin İhtiyacın Olan Her Şey', subtitle: 'CarbonTrace, güçlü takibi basit eylemle birleştirir.', feat1Title: 'Otomatik Takip', feat1Desc: 'Harcama verilerini güvenle bağla veya aktiviteleri manuel olarak kaydet. Hesaplamayı biz yapıyoruz.', feat2Title: 'Görsel Raporlar', feat2Desc: 'Emisyonlarının her ay tam olarak nereden geldiğini gösteren güzel, kolay anlaşılır panolar.', feat3Title: 'Sertifikalı Dengelemeler', feat3Desc: 'Dünya çapında doğrulanmış ağaçlandırma, temiz enerji ve karbon yakalama projelerine doğrudan finansman sağla.', feat4Title: 'Kişisel Hedefler', feat4Desc: 'Aylık veya yıllık azaltma hedefleri belirle ve ayak izini düşürmek için kişiselleştirilmiş ipuçları al.' },
    calculator: { title: 'Hızlı Karbon Hesaplayıcı', subtitle: 'Yıllık karbon ayak izinin kabaca tahminini bir dakikadan kısa sürede al.', lifestyle: 'Yaşam tarzın', reset: 'Sıfırla', transport: 'Haftalık araba yolculuğu', diet: 'Diyet tipi', electricity: 'Aylık elektrik faturası', vegan: 'Vegan', vegetarian: 'Vejeteryan', averageMeat: 'Ortalama et tüketimi', highMeat: 'Yüksek et tüketimi', footprint: 'Tahmini ayak izin', perYear: 'Yıllık CO₂e', globalAvg: 'Küresel ortalama', comparisonExcellent: 'Mükemmel! Küresel ortalamanın çok altındasın.', comparisonGood: 'Aferin! Küresel ortalamanın altındasın.', comparisonWarn: 'Küresel ortalamanın üzerindesin. Gelişime açık!', comparisonBad: 'Ayak izin ortalamadan önemli ölçüde yüksek.' },
    impact: { title: 'Öngörülen Etki', subtitle: '10.000 aktif kullanıcıyla CarbonTrace\'in ne başarabileceği. Bunlar, doğrulanmış dengeleme projesi verilerine dayalı ileriye dönük tahminlerdir.', impact1: 'Yıllık potansiyel CO₂ dengelemesi', impact2: 'Yıllık finanse edebileceğimiz ağaç', impact3: 'Destekleyebileceğimiz temiz enerji' },
    cta: { title: 'Ayak izini küçültmeye hazır mısın?', subtitle: 'Bekleme listesine katıl ve lansmanımızda tam erişimi ilk alanlardan biri ol.', placeholder: 'E-posta adresini gir', join: 'Bekleme Listesine Katıl', subscribed: 'Abone Olundu', noSpam: 'Spam yok. İstediğin zaman abonelikten çık.' },
    footer: { tagline: 'Takip et. Azalt. Dengele. Tekrarla.', copyright: 'Daha iyi bir gezegen için inşa edildi.' }
  },
  ko: {
    navbar: { problem: '문제', features: '기능', calculator: '계산기', impact: '영향', tryDemo: '데모 사용' },
    hero: { badge: '10,000명 이상의 초기 사용자 참여', title1: '발자국을 추적하세요.', title2: '지구를 구하세요.', subtitle: 'CarbonTrace는 일상 활동에서 자동으로 탄소 배출량을 계산하고 인증된 오프셋 프로젝트와 연결합니다. 작은 걸음이 큰 변화를 만듭니다.', cta1: '데모 계산기 사용', cta2: '더 알아보기', scroll: '스크롤하여 탐색' },
    problem: { title: '기후 위기는 개인의 문제입니다', subtitle: '기후 변화가 압도적으로 느껴질 수 있지만, 이는 우리 자신의 영향을 이해하는 것부터 시작됩니다. 대부분의 사람은 자신의 배출량이 실제로 어디에서 오는지 모릅니다.', stat1: '세계 화석연료 CO₂ 배출량 (약)', stat2: '1인당 연평균 화석연료 CO₂ 배출량', stat3: '산업화 이후 지구 온난화 상승폭', source1: '출처: Global Carbon Project (2023)', source2: '출처: Global Carbon Project / Our World in Data', source3: '출처: IPCC AR6 / WMO' },
    features: { title: '탄소 중립에 필요한 모든 것', subtitle: 'CarbonTrace는 강력한 추적 기능과 간단한 행동을 결합합니다.', feat1Title: '자동 추적', feat1Desc: '지출 데이터를 안전하게 연동하거나 활동을 수동으로 기록하세요. 계산은 우리가 합니다.', feat2Title: '시각적 보고서', feat2Desc: '아름답고 이해하기 쉬운 대시보드로 매월 배출원을 정확히 파악할 수 있습니다.', feat3Title: '인증 오프셋', feat3Desc: '전 세계의 검증된 재조림, 청정 에너지 및 탄소 포집 프로젝트에 직접 자금을 지원합니다.', feat4Title: '개인 목표', feat4Desc: '월간 또는 연간 감축 목표를 설정하고 발자국을 줄이기 위한 맞춤형 팁을 받아보세요.' },
    calculator: { title: '간편 탄소 계산기', subtitle: '1분도 채 걸리지 않아 연간 탄소 발자국의 대략적인 추정치를 얻을 수 있습니다.', lifestyle: '당신의 라이프스타일', reset: '초기화', transport: '주간 자동차 주행 거리', diet: '식단 유형', electricity: '월간 전기료', vegan: '비건', vegetarian: '채식', averageMeat: '평균 고기 소비', highMeat: '많은 고기 소비', footprint: '추정 발자국', perYear: '연간 CO₂e', globalAvg: '세계 평균', comparisonExcellent: '훌륭합니다! 세계 평균보다 훨씬 낮습니다.', comparisonGood: '잘했습니다! 세계 평균보다 낮습니다.', comparisonWarn: '세계 평균보다 높습니다. 개선의 여지가 있습니다!', comparisonBad: '당신의 발자국은 평균보다 상당히 높습니다.' },
    impact: { title: '예상 영향', subtitle: '10,000명의 활성 사용자를 확보했을 때 CarbonTrace가 달성할 수 있는 성과입니다. 이는 검증된 오프셋 프로젝트 데이터를 기반으로 한 전망 추정치입니다.', impact1: '잠재 연간 CO₂ 상쇄량', impact2: '매년 자금을 지원할 수 있는 나무', impact3: '지원할 수 있는 청정 에너지' },
    cta: { title: '발자국을 줄일 준비가 되셨나요?', subtitle: '대기자 명단에 등록하고 런칭 시 가장 먼저 전체 접근 권한을 받으세요.', placeholder: '이메일을 입력하세요', join: '대기자 명단 등록', subscribed: '구독 완료', noSpam: '스팸 없습니다. 언제든 구독 취소 가능합니다.' },
    footer: { tagline: '추적. 감소. 상쇄. 반복.', copyright: '더 나은 지구를 위해 만들어졌습니다.' }
  },
  it: {
    navbar: { problem: 'Problema', features: 'Funzionalità', calculator: 'Calcolatore', impact: 'Impatto', tryDemo: 'Prova demo' },
    hero: { badge: 'Unisciti a 10.000+ early adopters', title1: 'Traccia la Tua Impronta.', title2: 'Salva il Pianeta.', subtitle: 'CarbonTrace calcola automaticamente le tue emissioni di carbonio dalle attività quotidiane e ti collega a progetti di compensazione certificati. Piccoli passi, impatto enorme.', cta1: 'Prova il calcolatore demo', cta2: 'Scopri di più', scroll: 'Scorri per esplorare' },
    problem: { title: 'La Crisi Climatica è Personale', subtitle: 'Il cambiamento climatico può sembrare travolgente, ma inizia dalla comprensione del nostro impatto. La maggior parte delle persone non sa da dove provengono realmente le proprie emissioni.', stat1: 'Emissioni globali di CO₂ fossile (circa)', stat2: 'Media di CO₂ fossile per persona/anno', stat3: 'Aumento della temperatura globale dal periodo pre-industriale', source1: 'Fonte: Global Carbon Project (2023)', source2: 'Fonte: Global Carbon Project / Our World in Data', source3: 'Fonte: IPCC AR6 / WMO' },
    features: { title: 'Tutto ciò che Serve per Essere Carbon Neutral', subtitle: 'CarbonTrace combina un potente tracciamento con azioni semplici.', feat1Title: 'Tracciamento Automatico', feat1Desc: 'Collega in sicurezza i tuoi dati di spesa o registra le attività manualmente. Noi facciamo i conti.', feat2Title: 'Report Visuali', feat2Desc: 'Dashboard belle e facili da capire che mostrano esattamente da dove provengono le tue emissioni ogni mese.', feat3Title: 'Compensazioni Certificate', feat3Desc: 'Finanzia direttamente progetti verificati di riforestazione, energia pulita e cattura del carbonio in tutto il mondo.', feat4Title: 'Obiettivi Personali', feat4Desc: 'Imposta obiettivi di riduzione mensili o annuali e ricevi consigli personalizzati per ridurre la tua impronta.' },
    calculator: { title: 'Calcolatore Rapido del Carbonio', subtitle: 'Ottieni una stima approssimativa della tua impronta di carbonio annuale in meno di un minuto.', lifestyle: 'Il tuo stile di vita', reset: 'Reimposta', transport: 'Viaggi settimanali in macchina', diet: 'Tipo di dieta', electricity: 'Bolletta elettrica mensile', vegan: 'Vegano', vegetarian: 'Vegetariano', averageMeat: 'Consumo medio di carne', highMeat: 'Alto consumo di carne', footprint: 'La tua impronta stimata', perYear: 'CO₂e all\'anno', globalAvg: 'Media globale', comparisonExcellent: 'Eccellente! Sei ben al di sotto della media globale.', comparisonGood: 'Ottimo lavoro! Sei al di sotto della media globale.', comparisonWarn: 'Sei sopra la media globale. C\'è margine di miglioramento!', comparisonBad: 'La tua impronta è significativamente più alta della media.' },
    impact: { title: 'Impatto Previsto', subtitle: 'Cosa CarbonTrace potrebbe raggiungere con 10.000 utenti attivi. Si tratta di stime prospettiche basate su dati di progetti di compensazione verificati.', impact1: 'Potenziale compensazione annuale di CO₂', impact2: 'Alberi che potremmo finanziare ogni anno', impact3: 'Energia pulita che potremmo sostenere' },
    cta: { title: 'Pronto a ridurre la tua impronta?', subtitle: 'Unisciti alla lista d\'attesa e sii tra i primi ad avere accesso completo al lancio.', placeholder: 'Inserisci la tua email', join: 'Unisciti alla lista d\'attesa', subscribed: 'Iscritto', noSpam: 'Nessuno spam. Disiscriviti in qualsiasi momento.' },
    footer: { tagline: 'Traccia. Riduci. Compensa. Ripeti.', copyright: 'Costruito per un pianeta migliore.' }
  },
  vi: {
    navbar: { problem: 'Vấn đề', features: 'Tính năng', calculator: 'Máy tính', impact: 'Tác động', tryDemo: 'Dùng thử' },
    hero: { badge: 'Tham gia cùng 10.000+ ngưởi dùng sớm', title1: 'Theo Dõi Dấu Chân.', title2: 'Cứu Lấy Hành Tinh.', subtitle: 'CarbonTrace tự động tính toán lượng khí thải carbon từ các hoạt động hàng ngày của bạn và kết nối bạn với các dự án bù carbon được chứng nhận. Những bước nhỏ, tác động lớn.', cta1: 'Dùng thử máy tính mẫu', cta2: 'Tìm hiểu thêm', scroll: 'Cuộn để khám phá' },
    problem: { title: 'Khủng Hoảng Khí Hậu Là Chuyện Cá Nhân', subtitle: 'Biến đổi khí hậu có thể khiến bạn choáng ngợp, nhưng nó bắt đầu từ việc hiểu tác động của chính mình. Hầu hết mọi ngưởi không biết lượng khí thải của họ thực sự đến từ đâu.', stat1: 'Lượng phát thải CO₂ từ nhiên liệu hóa thạch toàn cầu (xấp xỉ)', stat2: 'Trung bình lượng CO₂ từ nhiên liệu hóa thạch mỗi ngưởi/năm', stat3: 'Mức tăng nhiệt độ toàn cầu kể từ thởi kỳ tiền công nghiệp', source1: 'Nguồn: Global Carbon Project (2023)', source2: 'Nguồn: Global Carbon Project / Our World in Data', source3: 'Nguồn: IPCC AR6 / WMO' },
    features: { title: 'Mọi Thứ Bạn Cần Để Trung Hòa Carbon', subtitle: 'CarbonTrace kết hợp theo dõi mạnh mẽ với hành động đơn giản.', feat1Title: 'Theo Dõi Tự Động', feat1Desc: 'Kết nối an toàn dữ liệu chi tiêu của bạn hoặc ghi lại hoạt động thủ công. Chúng tôi lo phép tính.', feat2Title: 'Báo Cáo Trực Quan', feat2Desc: 'Bảng điều khiển đẹp mắt, dễ hiểu cho biết chính xác nguồn phát thải của bạn mỗi tháng.', feat3Title: 'Bù Carbon Được Chứng Nhận', feat3Desc: 'Trực tiếp tài trợ các dự án trồng rừng, năng lượng sạch và thu giữ carbon được xác minh trên toàn cầu.', feat4Title: 'Mục Tiêu Cá Nhân', feat4Desc: 'Đặt mục tiêu giảm hàng tháng hoặc hàng năm và nhận mẹo cá nhân hóa để giảm dấu chân carbon.' },
    calculator: { title: 'Máy Tính Carbon Nhanh', subtitle: 'Ước tính dấu chân carbon hàng năm của bạn trong chưa đầy một phút.', lifestyle: 'Lối sống của bạn', reset: 'Đặt lại', transport: 'Quãng đường xe hơi hàng tuần', diet: 'Loại chế độ ăn', electricity: 'Hóa đơn điện hàng tháng', vegan: 'Ăn chay trường', vegetarian: 'Ăn chay', averageMeat: 'Tiêu thụ thịt trung bình', highMeat: 'Tiêu thụ thịt nhiều', footprint: 'Dấu chân ước tính của bạn', perYear: 'CO₂e mỗi năm', globalAvg: 'Trung bình toàn cầu', comparisonExcellent: 'Xuất sắc! Bạn thấp hơn nhiều so với trung bình toàn cầu.', comparisonGood: 'Làm tốt lắm! Bạn thấp hơn trung bình toàn cầu.', comparisonWarn: 'Bạn cao hơn trung bình toàn cầu. Còn chỗ để cải thiện!', comparisonBad: 'Dấu chân của bạn cao hơn đáng kể so với trung bình.' },
    impact: { title: 'Tác Động Dự Kiến', subtitle: 'Những gì CarbonTrace có thể đạt được với 10.000 ngưởi dùng tích cực. Đây là các ước tính dựa trên dữ liệu dự án bù carbon được xác minh.', impact1: 'Tiềm năng bù CO₂ hàng năm', impact2: 'Số cây chúng tôi có thể tài trợ hàng năm', impact3: 'Năng lượng sạch chúng tôi có thể hỗ trợ' },
    cta: { title: 'Sẵn sàng thu nhỏ dấu chân của bạn?', subtitle: 'Tham gia danh sách chờ và là một trong những ngưởi đầu tiên có quyền truy cập đầy đủ khi ra mắt.', placeholder: 'Nhập email của bạn', join: 'Tham gia danh sách chờ', subscribed: 'Đã đăng ký', noSpam: 'Không spam. Hủy đăng ký bất cứ lúc nào.' },
    footer: { tagline: 'Theo dõi. Giảm. Bù. Lặp lại.', copyright: 'Được xây dựng cho một hành tinh tốt đẹp hơn.' }
  },
  th: {
    navbar: { problem: 'ปัญหา', features: 'ฟีเจอร์', calculator: 'เครื่องคิดเลข', impact: 'ผลกระทบ', tryDemo: 'ลองใช้เดโม' },
    hero: { badge: 'เข้าร่วมกับผู้ใช้งานกว่า 10,000 คน', title1: 'ติดตามรอยเท้าของคุณ', title2: 'ช่วยโลก', subtitle: 'CarbonTrace คำนวณการปล่อยคาร์บอนจากกิจกรรมประจำวันโดยอัตโนมัติ และเชื่อมต่อคุณกับโครงการชดเชยที่ได้รับการรับรอง ก้าวเล็กๆ สร้างผลกระทบที่ยิ่งใหญ่', cta1: 'ลองใช้เครื่องคิดเลขเดโม', cta2: 'เรียนรู้เพิ่มเติม', scroll: 'เลื่อนเพื่อสำรวจ' },
    problem: { title: 'วิกฤติสภาพภูมิอากาศเป็นเรื่องส่วนตัว', subtitle: 'การเปลี่ยนแปลงสภาพภูมิอากาศอาจดูเหนือความสามารถ แต่มันเริ่มต้นจากการเข้าใจผลกระทบของเราเอง คนส่วนใหญ่ไม่รู้ว่าการปล่อยก๊าซของตัวเองมาจากไหนจริงๆ', stat1: 'ปริมาณ CO₂ จากเชื้อเพลิงฟอสซิลทั่วโลก (โดยประมาณ)', stat2: 'ค่าเฉลี่ย CO₂ จากเชื้อเพลิงฟอสซิลต่อคนต่อปี', stat3: 'ระดับการเพิ่มขึ้นของอุณหภูมิโลกนับตั้งแต่ยุคก่อนอุตสาหกรรม', source1: 'ที่มา: Global Carbon Project (2023)', source2: 'ที่มา: Global Carbon Project / Our World in Data', source3: 'ที่มา: IPCC AR6 / WMO' },
    features: { title: 'ทุกสิ่งที่คุณต้องการเพื่อเป็นกลางทางคาร์บอน', subtitle: 'CarbonTrace ผสมผสานการติดตามที่ทรงพลังเข้ากับการดำเนินการที่เรียบง่าย', feat1Title: 'การติดตามอัตโนมัติ', feat1Desc: 'เชื่อมต่อข้อมูลการใช้จ่ายของคุณอย่างปลอดภัย หรือบันทึกกิจกรรมด้วยตนเอง เราจัดการคำนวณให้', feat2Title: 'รายงานภาพ', feat2Desc: 'แดชบอร์ดที่สวยงามและเข้าใจง่าย แสดงให้เห็นอย่างชัดเจนว่าการปล่อยก๊าซของคุณมาจากไหนในแต่ละเดือน', feat3Title: 'โครงการชดเชยที่ได้รับการรับรอง', feat3Desc: 'สนับสนุนโครงการป่าไม้ พลังงานสะอาด และการดักจับคาร์บอนที่ได้รับการตรวจสอบทั่วโลกโดยตรง', feat4Title: 'เป้าหมายส่วนตัว', feat4Desc: 'ตั้งเป้าหมายการลดการปล่อยก๊าซรายเดือนหรือรายปี และรับคำแนะนำเฉพาะบุคคลเพื่อลดรอยเท้าคาร์บอน' },
    calculator: { title: 'เครื่องคิดเลขคาร์บอนด่วน', subtitle: 'ประเมินรอยเท้าคาร์บอนประจำปีของคุณโดยคร่าวๆ ในเวลาไม่ถึงหนึ่งนาที', lifestyle: 'ไลฟ์สไตล์ของคุณ', reset: 'รีเซ็ต', transport: 'ระยะทางขับรถประจำสัปดาห์', diet: 'ประเภทอาหาร', electricity: 'ค่าไฟฟ้ารายเดือน', vegan: 'มังสวิรัติ', vegetarian: 'เจ', averageMeat: 'บริโภคเนื้อสัตว์ปานกลาง', highMeat: 'บริโภคเนื้อสัตว์มาก', footprint: 'รอยเท้าประเมินของคุณ', perYear: 'CO₂e ต่อปี', globalAvg: 'ค่าเฉลี่ยทั่วโลก', comparisonExcellent: 'ยอดเยี่ยม! คุณต่ำกว่าค่าเฉลี่ยทั่วโลกมาก', comparisonGood: 'ทำได้ดี! คุณต่ำกว่าค่าเฉลี่ยทั่วโลก', comparisonWarn: 'คุณสูงกว่าค่าเฉลี่ยทั่วโลก ยังมีที่ให้ปรับปรุง!', comparisonBad: 'รอยเท้าของคุณสูงกว่าค่าเฉลี่ยอย่างมีนัยสำคัญ' },
    impact: { title: 'ผลกระทบที่คาดการณ์', subtitle: 'สิ่งที่ CarbonTrace อาจบรรลุได้หากมีผู้ใช้งานที่ใช้งานอย่างต่อเนื่อง 10,000 คน นี่คือการประมาณการเชิงคาดการณ์จากข้อมูลโครงการชดเชยที่ได้รับการรับรอง', impact1: 'ศักยภาพการชดเชย CO₂ ต่อปี', impact2: 'ต้นไม้ที่เราอาจปลูกได้ต่อปี', impact3: 'พลังงานสะอาดที่เราอาจสนับสนุน' },
    cta: { title: 'พร้อมที่จะลดรอยเท้าของคุณหรือยัง?', subtitle: 'เข้าร่วมรายชื่อรอและเป็นหนึ่งในคนแรกที่ได้รับสิทธิ์เข้าถึงแบบเต็มรูปแบบเมื่อเปิดตัว', placeholder: 'ป้อนอีเมลของคุณ', join: 'เข้าร่วมรายชื่อรอ', subscribed: 'สมัครแล้ว', noSpam: 'ไม่มีสแปม ยกเลิกการสมัครได้ตลอดเวลา' },
    footer: { tagline: 'ติดตาม ลด ชดเชย ทำซ้ำ', copyright: 'สร้างขึ้นเพื่อโลกที่ดีกว่า' }
  },
  pl: {
    navbar: { problem: 'Problem', features: 'Funkcje', calculator: 'Kalkulator', impact: 'Wpływ', tryDemo: 'Wypróbuj demo' },
    hero: { badge: 'Dołącz do 10 000+ wczesnych użytkowników', title1: 'Śledź Swój Ślad.', title2: 'Ocal Planetę.', subtitle: 'CarbonTrace automatycznie oblicza emisję dwutlenku węgla z codziennych aktywności i łączy Cię z certyfikowanymi projektami kompensacyjnymi. Małe kroki, ogromny wpływ.', cta1: 'Wypróbuj kalkulator demo', cta2: 'Dowiedz się więcej', scroll: 'Przewiń, aby odkrywać' },
    problem: { title: 'Kryzys Klimatyczny Jest Osobisty', subtitle: 'Zmiany klimatyczne mogą przytłaczać, ale zaczynają się od zrozumienia własnego wpływu. Większość ludzi nie wie, skąd naprawdę pochodzą ich emisje.', stat1: 'Globalne emisje CO₂ z paliw kopalnych (ok.)', stat2: 'Średnie emisje CO₂ z paliw kopalnych na osobę/rok', stat3: 'Wzrost temperatury globalnej od ery przedindustrialnej', source1: 'Źródło: Global Carbon Project (2023)', source2: 'Źródło: Global Carbon Project / Our World in Data', source3: 'Źródło: IPCC AR6 / WMO' },
    features: { title: 'Wszystko, Czego Potrzebujesz, Aby Być Węglowo Neutralny', subtitle: 'CarbonTrace łączy potężne śledzenie z prostym działaniem.', feat1Title: 'Automatyczne Śledzenie', feat1Desc: 'Bezpiecznie połącz swoje dane o wydatkach lub rejestruj aktywności ręcznie. My wykonujemy obliczenia.', feat2Title: 'Wizualne Raporty', feat2Desc: 'Piękne, łatwe do zrozumienia panele pokazujące dokładnie, skąd pochodzą Twoje emisje każdego miesiąca.', feat3Title: 'Certyfikowane Kompensacje', feat3Desc: 'Bezpośrednio finansuj zweryfikowane projekty zalesiania, czystej energii i wychwytywania węgla na całym świecie.', feat4Title: 'Osobiste Cele', feat4Desc: 'Ustal miesięczne lub roczne cele redukcji i otrzymuj spersonalizowane wskazówki, jak zmniejszyć swój ślad.' },
    calculator: { title: 'Szybki Kalkulator Węglowy', subtitle: 'Uzyskaj przybliżoną ocenę rocznego śladu węglowego w mniej niż minutę.', lifestyle: 'Twój styl życia', reset: 'Resetuj', transport: 'Tygodniowy przejazd samochodem', diet: 'Typ diety', electricity: 'Miesięczny rachunek za prąd', vegan: 'Wegańska', vegetarian: 'Wegetariańska', averageMeat: 'Średnie spożycie mięsa', highMeat: 'Wysokie spożycie mięsa', footprint: 'Twój szacunkowy ślad', perYear: 'CO₂e rocznie', globalAvg: 'Średnia globalna', comparisonExcellent: 'Znakomite! Jesteś znacznie poniżej średniej globalnej.', comparisonGood: 'Dobra robota! Jesteś poniżej średniej globalnej.', comparisonWarn: 'Jesteś powyżej średniej globalnej. Jest miejsce na poprawę!', comparisonBad: 'Twój ślad jest znacznie wyższy niż średnia.' },
    impact: { title: 'Szacowany Wpływ', subtitle: 'Co CarbonTrace mógłby osiągnąć z 10 000 aktywnymi użytkownikami. Są to szacunki prospektywne oparte na danych zweryfikowanych projektów kompensacyjnych.', impact1: 'Potencjalna roczna kompensacja CO₂', impact2: 'Drzewa, które moglibyśmy finansować rocznie', impact3: 'Czysta energia, którą moglibyśmy wspierać' },
    cta: { title: 'Gotowy, aby zmniejszyć swój ślad?', subtitle: 'Dołącz do listy oczekujących i bądź jednym z pierwszych, którzy uzyskają pełen dostęp po premierze.', placeholder: 'Wpisz swój email', join: 'Dołącz do listy', subscribed: 'Zapisano', noSpam: 'Bez spamu. Wypisz się w każdej chwili.' },
    footer: { tagline: 'Śledź. Redukuj. Kompensuj. Powtarzaj.', copyright: 'Zbudowane dla lepszej planety.' }
  },
  nl: {
    navbar: { problem: 'Probleem', features: 'Functies', calculator: 'Rekenmachine', impact: 'Impact', tryDemo: 'Probeer demo' },
    hero: { badge: 'Sluit je aan bij 10.000+ early adopters', title1: 'Volg Je Voetafdruk.', title2: 'Red de Planeet.', subtitle: 'CarbonTrace berekent automatisch je koolstofemissies uit dagelijkse activiteiten en verbindt je met gecertificeerde compensatieprojecten. Kleine stappen, enorme impact.', cta1: 'Probeer de demo-rekenmachine', cta2: 'Leer meer', scroll: 'Scroll om te verkennen' },
    problem: { title: 'De Klimaatcrisis is Persoonlijk', subtitle: 'Klimaatverandering kan overweldigend aanvoelen, maar het begint met het begrijpen van onze eigen impact. De meeste mensen weten niet waar hun emissies eigenlijk vandaan komen.', stat1: 'Wereldwijde fossiele CO₂-emissies (ca.)', stat2: 'Gemiddelde fossiele CO₂ per persoon/jaar', stat3: 'Wereldwijde temperatuurstijging sinds het pre-industriële tijdperk', source1: 'Bron: Global Carbon Project (2023)', source2: 'Bron: Global Carbon Project / Our World in Data', source3: 'Bron: IPCC AR6 / WMO' },
    features: { title: 'Alles Wat Je Nodig Hebt om Koolstofneutraal te Worden', subtitle: 'CarbonTrace combineert krachtige tracking met eenvoudige actie.', feat1Title: 'Automatisch Tracking', feat1Desc: 'Koppel veilig je uitgavengegevens of log activiteiten handmatig. Wij doen de berekening.', feat2Title: 'Visuele Rapporten', feat2Desc: 'Mooie, gemakkelijk te begrijpen dashboards die precies laten zien waar je emissies vandaan komen.', feat3Title: 'Gecertificeerde Compensaties', feat3Desc: 'Financier direct geverifieerde herbebossings-, schone energie- en koolstofafvangprojecten over de hele wereld.', feat4Title: 'Persoonlijke Doelen', feat4Desc: 'Stel maandelijkse of jaarlijkse reductiedoelen en ontvang gepersonaliseerde tips om je voetafdruk te verkleinen.' },
    calculator: { title: 'Snelle Koolstof Rekenmachine', subtitle: 'Krijg een ruwe schatting van je jaarlijkse koolstofvoetafdruk in minder dan een minuut.', lifestyle: 'Jouw levensstijl', reset: 'Resetten', transport: 'Wekelijkse autoritten', diet: 'Type dieet', electricity: 'Maandelijks elektriciteitsfactuur', vegan: 'Veganistisch', vegetarian: 'Vegetarisch', averageMeat: 'Gemiddeld vleesverbruik', highMeat: 'Hoog vleesverbruik', footprint: 'Je geschatte voetafdruk', perYear: 'CO₂e per jaar', globalAvg: 'Wereldwijd gemiddelde', comparisonExcellent: 'Uitstekend! Je ligt ver onder het wereldwijde gemiddelde.', comparisonGood: 'Goed gedaan! Je ligt onder het wereldwijde gemiddelde.', comparisonWarn: 'Je ligt boven het wereldwijde gemiddelde. Er is ruimte voor verbetering!', comparisonBad: 'Je voetafdruk is aanzienlijk hoger dan het gemiddelde.' },
    impact: { title: 'Verwachte Impact', subtitle: 'Wat CarbonTrace zou kunnen bereiken met 10.000 actieve gebruikers. Dit zijn vooruitkijkende schattingen gebaseerd op gegevens van geverifieerde compensatieprojecten.', impact1: 'Potentiële jaarlijkse CO₂-compensatie', impact2: 'Bomen die we jaarlijks zouden kunnen financieren', impact3: 'Schone energie die we zouden kunnen ondersteunen' },
    cta: { title: 'Klaar om je voetafdruk te verkleinen?', subtitle: 'Meld je aan voor de wachtlijst en wees een van de eersten die volledige toegang krijgt bij de lancering.', placeholder: 'Vul je email in', join: 'Meld je aan', subscribed: 'Ingeschreven', noSpam: 'Geen spam. Altijd uitschrijven mogelijk.' },
    footer: { tagline: 'Volg. Verminder. Compenseer. Herhaal.', copyright: 'Gebouwd voor een betere planeet.' }
  },
}

export function getTranslation(lang) {
  return translations[lang] || translations['en']
}

export default translations
